---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  # require_chef_omnibus: false
  require_ansible_omnibus: true
  # require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: centos-8
  - name: centos-7
  - name: centos-6
    ## FIXME! workaround Ansible 2.2+/cryptography: https://github.com/ansible/ansible/issues/276 no attribute 'HAVE_DECL_MPZ_POWM_SEC'
    provisioner:
      ## Desired version, only affects apt-get installs
      ansible_version: 2.1.2.0
## not supported by kitchen/chef install
#  - name: alpine-3.10

suites:
  - name: default
    run_list:
    attributes:
  - name: full
    run_list:
    attributes:
  - name: default-gpg
    run_list:
    attributes:
    includes:
      - ubuntu-18.04
