---

- name: Configure journald
  ansible.builtin.template:
    src: "{{ journald_conf_template }}.j2"
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart systemd-journald
