---

- name: Verify
  hosts: "{{ playbook_hosts | default('all') }}"
  vars:
    files_test:
      - /etc/rsyslog.d/50-default.conf
      - /etc/rsyslog.d/10-remote-syslog.conf
    is_container: false
  pre_tasks:
    - name: Debug | var ansible_facts['virtualization_type']
      ansible.builtin.debug:
        var: ansible_facts['virtualization_type']
    - name: Set fact is_container
      ansible.builtin.set_fact:
        is_container: true
      when: >
        (ansible_facts['virtualization_type'] is defined and
          (ansible_facts['virtualization_type'] == "docker"
           or ansible_facts['virtualization_type'] == "containerd"
           or ansible_facts['virtualization_type'] == "container"
          )
        )
    - name: Ensure procps package is present
      ansible.builtin.package:
        name: procps
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: Debian | Ensure ps/pgrep is present
      ansible.builtin.package:
        name: procps
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: Debian | set fact
      ansible.builtin.set_fact:
        files_test:
          - /etc/rsyslog.d/10-remote-syslog.conf
      when: ansible_facts['distribution'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'
  tasks:
    - name: Ensure rsyslog config is present
      ansible.builtin.stat:
        path: "{{ item }}"
      register: cfg
      with_items: "{{ files_test }}"
    - name: Validate config present
      ansible.builtin.assert:
        that: item.stat.exists and item.stat.size != 0
      with_items: "{{ cfg.results }}"

    - name: Check all processes
      ansible.builtin.command: ps aux
      changed_when: false
      register: psa
    - name: Debug | ps aux output
      ansible.builtin.debug:
        var: psa
        verbosity: 1

    - name: Ensure syslog process is running
      ansible.builtin.command: pgrep rsyslogd
      register: ps
      changed_when: false
      failed_when: false
    - name: Validate ps output
      ansible.builtin.assert:
        that: ps.stdout | length > 0
      when:
        - not is_container|bool

    - name: Get few logs
      ansible.builtin.command:
        cmd: tail -5 /var/log/syslog
      register: logs
      changed_when: false
      failed_when: false
    - name: Ensure year is present (full timestamp)
      ansible.builtin.assert:
        that:
          - "ansible_facts['date_time'].year in logs.stdout"
      when:
        - not is_container|bool
